### ISSUE TITLE
Store result

### ISSUE THREAD

**Issue by alvin8t** [Stevertus/mcscript#3]
Hey,
I absolutely love what you are doing with this, however, in grouping... there is a slight bug when trying to group store. I'm not finding a way to do something like
`execute store result bossbar <name> value run scoreboard players get <selector> <objective>`
I have tried to do
```
store('result bossbar <selector> value') {
    scoreboard players get <selector> <objective>
}
```
However, it complies to
`execute store(result bossbar <selector> value) run scoreboard players get <selector> <objective>`

Unless I'm reading the documentation wrong, I believe that this is a bug. If not then sorry 😃 

Thanks... and Keep up the great work,
Alex (alvin8t)

**Comment by Stevertus** [comment]
This is not a bug. It is not supported by Minecraft Script, because it makes no sense to group execute store.
Mostly you use only one command and that is not the pupose of command grouping.
Please just use: `/execute store result bossbar <name> value run scoreboard players get <selector> <objective>`
